name: email_repository
description: A repository that provides an abstraction layer over email operations.
repository: https://github.com/flutter-news-app-full-source-code/email-repository
publish_to: none
version: 1.0.1

environment:
  sdk: ^3.9.0

dependencies:
  core:
    git:
      url: https://github.com/flutter-news-app-full-source-code/core.git
      ref: v1.3.1
  email_client:
    git:
      url: https://github.com/flutter-news-app-full-source-code/email-client.git
      ref: v1.0.1

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.28.0
  very_good_analysis: ^9.0.0
